### PR TITLE
added Hamilton fansite homework

### PR DESCRIPTION
**Pull request by j-tws**
_If you had no problems you can just leave it empty_

- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible)
- 7/10
- Was there anything that you struggled with?
Generally trying to get use to css and understand what it does. Sometimes things you feel easy is actually hard to do.
Layout is hard and need to do a lot of practice yet.

- Is there any particular code you want me to look into?
HTML and CSS coding conventions. Which areas am i doing wrong

- Is there anything that you'd like some further information on?
- Roughly how long did it take?
- 5 hours+

### CODE REVIEW

**Comment by kristabel-wong** [comment]
Woah this looks good Justin! I'm impressed you even started with animations. That moving moon is sick!

So far it looks good to me, your coding conventions are fine!

**Comment by j-tws** [comment]
Thanks Kris! 😊 Took me some time to make the earth thingy to happen.

Kind regards,
Justin Tan

**Comment by kristabel-wong** [comment]
Also, you don't need to use target="_blank" for each of the links. You only want to use it if it will take you to an external site and you want to open the link in addition to your site. 

right now, im exploring your page, but its opened a new tab for each of the links (5 tabs) but you can just have one tab to navigate the same site

**Comment by j-tws** [comment]
Right I'll note that. Apologies to flood your browser unnecessary!

Kind regards
Justin Tan

**Pull request merged**
